uccser/cs-field-guide

- text/en/chapters/programming-languages.md
Really cool to find out my MIPS assembler & emulator are featured in your textbook. I thought a specific credit would be appropriate.
> Credit the specific MIPS emulator linked to here

- text/en/chapters/human-computer-interaction.md
> Make small corrections to HCI chapter

- text/en/chapters/programming-languages.md
> Make small corrections to Programming chapter

- text/en/chapters/coding-compression.md
Some small editorial and typo fixes.
> Fix editorial and typos in Compression chapter

- text/en/chapters/data-representation.md
> Subject-verb agreement

- text/en/404.md
> Remove unneeded "been" in 404 page

- text/en/chapters/computer-graphics.md
Fix some formatting and text typos.
Also fix a couple of issues with the Bresenham line solution, and
clarify behaviour of the 2D rotation matrix.
> Fix small issues in Graphics chapter

- text/en/chapters/coding-encryption.md
Including fixing broken glossary link for "digital signature".
> Fix several typos in Encryption chapter

- interactives/frequency-analysis/README.md
- interactives/frequency-analysis/package.json
This adds README.md to frequency analysis and adds devDependencies to package.json
> Freq Analysis Added README.md

- interactives/sha2/README.md
- interactives/sha2/package.json
This adds README.md and adds needed dependencies to package.json
> Added README.md

- text/en/chapters/complexity-tractability.md
Fix small typos in tractability chapter.
*Put an `x` in the boxes that apply. You can also fill these out after creating the pull request. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your change.*
> Fix small typos in tractability chapter

- text/en/curriculum-guides/apcsp/guide-algorithms-introduction.md
- text/en/curriculum-guides/apcsp/guide-programming-introduction.md
- text/en/curriculum-guides/apcsp/guide-the-internet-introduction.md
- text/en/curriculum-guides/apcsp/index.md
Updating this guide to match the minor changes to the curriculum in the Fall 2016 version.
_Put an `x` in the boxes that apply. You can also fill these out after creating the pull request. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your change._
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc. Feel free to add any images that might be helpful to understand the initial problem/solution.
> Apcsp framework updates

- subtitles/computer_science_buskers_error_detection.vtt
- subtitles/csfg_algorithms_race.vtt
- subtitles/csfg_artificial_intelligence_intro.vtt
- subtitles/csfg_computer_graphics_intro.vtt
- subtitles/csfg_computer_vision_intro.vtt
- subtitles/csfg_human_computer_interaction_intro.vtt
- subtitles/csfg_introduction.vtt
- subtitles/csfg_software_engineering_intro.vtt
- subtitles/csfg_tractability_intro.vtt
- subtitles/formal_languages_intro.vtt
- subtitles/image_compression_making_contact.vtt
- subtitles/network_protocols_intro.vtt
Added new subtitles folder in top level containing youtube subtitles for field guide videos.
Subtitles added for videos:
> Added Subtitles

- subtitles/fsa_1_intro.vtt
- subtitles/fsa_2_uses.vtt
- subtitles/fsa_3_looks.vtt
- subtitles/fsa_4_example_sentence.vtt
- subtitles/fsa_5_common_terms.vtt
- subtitles/fsa_6_build_our_own.vtt
- subtitles/fsa_7_more_states.vtt
- subtitles/fsa_8_finishing.vtt
- subtitles/regex_1_intro.vtt
- subtitles/regex_2_basics.vtt
- subtitles/regex_3_extended.vtt
- subtitles/regex_4_fsa.vtt
- subtitles/regex_5_example.vtt
Added English subtitles for YouTube videos.
Videos affected are:
- Finite State Automata videos 1-8
- Regular Expressions videos 1-5
*Put an `x` in the boxes that apply. You can also fill these out after creating the pull request. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your change.*
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc. Feel free to add any images that might be helpful to understand the initial problem/solution.
> English Subtitles for FSA and RE videos

- csfieldguide/utils/custom_converter_templates/image.html
- csfieldguide/utils/custom_converter_templates/panel.html
- csfieldguide/utils/custom_converter_templates/video.html
This PR exists because I got sick of tiny videos, giant images, and panels blending in to the text.
These are placeholder html templates, and expect them to be replaced with something more permanent in the near future.
> Updates to ui to make viewing chapters less terrible

- generator/html-templates.conf
- text/en/curriculum-guides/ncea/as91885/index.md
- text/en/curriculum-guides/ncea/as91886/index.md
- text/en/curriculum-guides/ncea/as91887/index.md
- text/en/curriculum-guides/ncea/index.md
- text/en/settings.yaml
This PR adds three basic guides for the new NCEA curriculum guides.
> Add 2018 NCEA curriculum guides

- Dockerfile
- requirements/base.txt
Also removed redundant dependencies
> Updated dockerfile to use latest uccser docker image

- csfieldguide/interactives/content/en/interactives.yaml
- csfieldguide/static/interactives/sorting-algorithm-comparison/css/style.css
- csfieldguide/templates/interactives/sorting-algorithm-comparison.html
Refactor the sorting-algorithm-comparison interactive to use the Django web framework. Relates to #622.
> Refactor sorting-algorithm-comparison interactive.

- csfieldguide/interactives/content/en/interactives.yaml
- csfieldguide/static/interactives/high-score-boxes/js/script.js
- csfieldguide/templates/interactives/high-score-boxes.html
Refactor the high-score-boxes interactive to use the Django web framework. Relates to #622.
> Refactor high-score-boxes interactive.

- .travis.yml
- Adds names to jobs
- Removes develop deploy checks on push commits on non develop branches
> Update Travis CI config file

- README.md
- csfieldguide/chapters/content/en/coding-encryption/sections/substitution-ciphers.md
- csfieldguide/chapters/content/en/coding-error-control/sections/the-parity-magic-trick.md
- csfieldguide/chapters/content/en/complexity-and-tractability/sections/other-intractable-problems.md
- csfieldguide/chapters/content/en/computer-graphics/sections/further-reading.md
- csfieldguide/chapters/content/en/computer-vision/sections/further-reading.md
- csfieldguide/chapters/content/en/data-representation/sections/text.md
- csfieldguide/chapters/content/en/formal-languages/sections/finite-state-automata.md
- csfieldguide/chapters/content/en/formal-languages/sections/further-reading.md
- csfieldguide/chapters/content/en/formal-languages/sections/grammars-and-parsing.md
- csfieldguide/chapters/content/en/introduction/introduction.md
- csfieldguide/chapters/content/en/programming-languages/sections/further-reading.md
- csfieldguide/chapters/content/en/software-engineering/sections/agile-software-development.md
- csfieldguide/chapters/content/en/software-engineering/sections/further-reading.md
- csfieldguide/chapters/content/en/software-engineering/sections/testing.md
- csfieldguide/static/interactives/regular-expression-filter/README.md
- csfieldguide/static/interactives/searching-algorithms/index.html
- csfieldguide/static/interactives/sorting-algorithms/index.html
- csfieldguide/templates/appendices/contributors.html
- csfieldguide/tests/chapters/loaders/assets/chapters/en/no-icon/no-icon.md
- text/en/curriculum-guides/ncea/level-3/software-engineering-methodologies.md
> Fix broken links

- csfieldguide/chapters/content/en/algorithms/algorithms.md
- csfieldguide/chapters/content/en/algorithms/sections/searching.md
- csfieldguide/static/interactives/high-score-boxes/js/script.js
Rephrasing of some sentences and an interactive fix for the Algorithms chapter.
> Algorithms tidy up for translations

- csfieldguide/static/scss/website.scss
- csfieldguide/templates/interactives/binary-mode-calculator.html
- csfieldguide/templates/interactives/confused-buttons.html
- csfieldguide/templates/interactives/confusing-error.html
- csfieldguide/templates/interactives/off-by-one.html
> Remove pointer events for 'uninteractives'

- csfg
> Copy jsi18n to staticfiles.

- csfieldguide/package.json
- csfieldguide/static/interactives/caesar-cipher/js/caesar.js
- csfieldguide/static/interactives/unicode-binary/js/unicode-binary.js
This resolves the build failing on a non-existent package. These interactives will need to fixed before releasing.
> Remove references to jquery-text-input (fixes #790)

- csfieldguide/chapters/content/en/programming-languages/sections/machine-code.md
> Fix typo in Programming Languages chapter

- csfieldguide/chapters/content/en/data-representation/data-representation.md
- csfieldguide/chapters/content/en/data-representation/sections/images-and-colours.md
- csfieldguide/config/settings/local.py
- csfieldguide/templates/interactives/binary-cards.html
- Fix incorrect representation of 19 in binary
- Fix curly brace in Binary Cards interactive
- Fix minor typo in Images And Colours section
> Fix content errors in data rep chapter

- csfieldguide/chapters/content/en/human-computer-interaction/human-computer-interaction.md
- csfieldguide/chapters/content/en/human-computer-interaction/sections/interface-usability.md
- csfieldguide/chapters/content/en/human-computer-interaction/sections/the-whole-story.md
- csfieldguide/chapters/content/en/human-computer-interaction/sections/usability-heuristics.md
- csfieldguide/config/settings/local.py
- csfieldguide/static/interactives/number-generator/js/checksum-generator.js
- csfieldguide/static/interactives/rsa-jsencrypt/js/rsa-jsencrypt.js
- csfieldguide/templates/interactives/base-calculator.html
- csfieldguide/templates/interactives/colour-matcher.html
- csfieldguide/templates/interactives/deceiver.html
- csfieldguide/templates/interactives/hex-background-colour.html
- csfieldguide/templates/interactives/number-generator.html
- csfieldguide/templates/interactives/rsa-jsencrypt.html
- csfieldguide/templates/interactives/trainsylvania-planner.html
> Source string corrections for translations

- csfieldguide/chapters/content/en/programming-languages/programming-languages.md
- csfieldguide/chapters/content/en/programming-languages/sections/a-babel-of-programming-languages.md
- csfieldguide/chapters/content/en/programming-languages/sections/the-whole-story.md
- Fix typos
- Fix grammatical errors
- Fix example output of example Python code
> Fix content errors in Programming Languages chapter

- csfg
> Deprecate 'dev' command for helper script

- csfieldguide/static/scss/_core-variables.scss
- csfieldguide/static/scss/website.scss
- csfieldguide/templates/404.html
- csfieldguide/templates/base.html
- csfieldguide/templates/general/index.html
- csfieldguide/templates/interactives/awful-calculator.html
- csfieldguide/templates/interactives/base/whole-page.html
- csfieldguide/templates/search/search.html
This allows interactives to use all screen estate except for navbar.
> Flexbox structure

- infrastructure/dev-deploy/deploy-static-files.sh
> Fix bug where interactive thumbnails are not deployed.

- csfieldguide/static/interactives/binary-cards/css/binary-cards.css
> Prevent back of binary cards showing through once flipped

- infrastructure/nginx/Dockerfile
This PR changes the permissions on the /app/ folder to:
- Readable by User, Group and World.
- Writable by User.
- Executable by User, Group and World.
Fixes permission errors when on the University network (should not affect other Dev's).
> Change app folder permissions

- csfieldguide/static/scss/_core-variables.scss
- csfieldguide/static/scss/website.scss
- csfieldguide/templates/chapters/chapter_section.html
Updates the navigation bar colours for the table of contents to fit the csfg theme.
I made the hover colour on the nav links slightly darker than $csfg so there was a more noticable change in colour upon hovering over the link.
Resolves #935
> Change navbar colours for table of contents.

- csfieldguide/templates/interactives/fsa-washing-machine.html
> Center fsa-washing-machine interactive in whole-page mode.

- csfieldguide/static/scss/codemirror.scss
> Remove .css extension.

- csfieldguide/chapters/content/en/algorithms/sections/searching.md
Resolves #973 and also fixes bullet point formatting.
> Remove reference to old searching interactive.

- csfieldguide/chapters/content/en/software-engineering/sections/analysis.md
> Minor content fix

- csfieldguide/chapters/content/en/data-representation/sections/getting-started.md
- csfieldguide/interactives/content/structure/interactives.yaml
- csfieldguide/static/interactives/dot-combinations/README.md
- csfieldguide/static/interactives/dot-combinations/js/dot-combinations.js
- csfieldguide/static/interactives/dot-combinations/scss/dot-combinations.scss
- csfieldguide/templates/interactives/dot-combinations.html
Resolves #219 by recreating the dot-combinations uninteractive as an interactive activity
> 1001 ways to Recreate dot-combinations as interactive

- csfg
> Remove docker volumes when the ./csfg end command is run

- csfieldguide/chapters/content/en/data-representation/sections/numbers.md
Resolves #303 by mentioning that two's complement will be covered later in the section
> reference later-on section about two's complement in chapter

- csfieldguide/static/interactives/dot-combinations/js/dot-combinations.js
- csfieldguide/templates/interactives/dot-combinations.html
Adds singular form for number of patterns found, as well as plural
> Add proper singular form to dot-combinations interactive text

- csfieldguide/templates/general/index.html
> Add student mode button to homepage if in teacher mode

- docs/source/author/content_style_guide.rst
Resolves  #578
The list of major additions can be found on that page
> Update content style guide

- .travis.yml
- infrastructure/install_google_cloud_sdk.sh
> Add temporary fix for deploying static files

- docs/source/changelog.rst
Resolves #1037 (changelog is now in and to a a good standard)
> Minor changelog fixes

- csfieldguide/chapters/content/en/algorithms/sections/searching.md
- csfieldguide/chapters/content/en/algorithms/sections/the-whole-story.md
- csfieldguide/chapters/content/en/algorithms/sections/whats-the-big-picture.md
- csfieldguide/chapters/content/en/coding-encryption/sections/cryptosystems-used-in-practice.md
- csfieldguide/chapters/content/en/coding-encryption/sections/the-key-distribution-problem.md
- csfieldguide/chapters/content/en/data-representation/sections/images-and-colours.md
- csfieldguide/chapters/content/en/data-representation/sections/whats-the-big-picture.md
- csfieldguide/chapters/content/en/glossary/bozo-search.md
- csfieldguide/chapters/content/en/human-computer-interaction/sections/interface-usability.md
- csfieldguide/chapters/content/en/human-computer-interaction/sections/users-and-tasks.md
- csfieldguide/chapters/content/en/introduction/sections/how-to-use-this-guide.md
- csfieldguide/chapters/content/en/network-communication-protocols/network-communication-protocols.md
- csfieldguide/chapters/content/en/programming-languages/sections/machine-code.md
Re-fix some fixes (#1018) that were un-fixed
Make some new fixes
Add glossary term for bozo search (related to #1017)
> Many more content fixes

- csfieldguide/static/scss/website.scss
> fix floating elements overlapping subsection divider

- csfieldguide/templates/base.html
> Add Curriculum Guides to useful links

- csfieldguide/static/scss/website.scss
- csfieldguide/templates/general/index.html
> Center homepage icons on firefox mobile.

- csfieldguide/chapters/content/en/computer-vision/sections/face-recognition.md
> Remove references to Picasa

- csfieldguide/chapters/content/en/glossary/protocol.md
- csfieldguide/chapters/content/en/glossary/usability.md
- csfieldguide/chapters/content/en/human-computer-interaction/sections/interface-usability.md
- csfieldguide/chapters/content/en/human-computer-interaction/sections/usability-heuristics.md
- csfieldguide/chapters/content/en/human-computer-interaction/sections/users-and-tasks.md
- csfieldguide/chapters/content/en/human-computer-interaction/sections/whats-the-big-picture.md
General content/consistency fixes in the HCI chapter, and add two new glossary entries
- Protocol
- Usability
The latter relates to #1017
> HCI chapter fixes and add glossary entries

- csfieldguide/templates/appendices/contributors.html
- Fix spelling of contributor 'Gitter Badger'
- Remove duplicate of contributor 'Goldob'
- Add writer 'Hayley van Waas'
> Improve list of contributors

- csfieldguide/chapters/content/en/data-representation/sections/getting-started.md
- csfieldguide/chapters/content/en/data-representation/sections/images-and-colours.md
- csfieldguide/chapters/content/en/data-representation/sections/numbers.md
- csfieldguide/chapters/content/en/data-representation/sections/program-instructions.md
- csfieldguide/chapters/content/en/data-representation/sections/text.md
- csfieldguide/chapters/content/en/data-representation/sections/the-whole-story.md
- csfieldguide/chapters/content/en/data-representation/sections/whats-the-big-picture.md
- csfieldguide/chapters/content/en/glossary/character.md
- csfieldguide/chapters/content/en/glossary/complement.md
General content fixes and two new Glossary entries for the Data Representation chapter:
The latter relates to #1017 
- Complement
- Character (in text)
My branch name might have broken something, not sure
> Content improvement + add glossary entries for Data Representation chapter

- csfieldguide/chapters/content/en/algorithms/sections/searching.md
- csfieldguide/static/interactives/searching-algorithms/js/searching-algorithms.js
> Fix url parameters in searching boxes interactive

- csfieldguide/chapters/content/en/artificial-intelligence/artificial-intelligence.md
- csfieldguide/chapters/content/en/artificial-intelligence/sections/chatterbots-and-the-turing-test.md
- csfieldguide/chapters/content/en/artificial-intelligence/sections/whats-the-big-picture.md
- csfieldguide/chapters/content/en/glossary/artificial-intelligence.md
- csfieldguide/chapters/content/en/glossary/intelligent-systems.md
New entry `artificial-intelligence`
Link to entries already in the glossary
Contributes to #1017
> Add glossary entries for AI chapter

- csfieldguide/config/__init__.py
- docs/source/changelog.rst
Update links in changelog. Resolves #1141
> Hotfix 3.0.5

- csfieldguide/chapters/content/en/complexity-and-tractability/complexity-and-tractability.md
- csfieldguide/chapters/content/en/complexity-and-tractability/sections/algorithms-problems-and-speed-limits.md
- csfieldguide/chapters/content/en/complexity-and-tractability/sections/bin-packing-problem.md
- csfieldguide/chapters/content/en/complexity-and-tractability/sections/the-travelling-salesman-problem.md
- csfieldguide/chapters/content/en/complexity-and-tractability/sections/the-whole-story.md
- csfieldguide/chapters/content/en/complexity-and-tractability/sections/whats-the-big-picture.md
- csfieldguide/chapters/content/en/glossary/asymptotic-complexity.md
- csfieldguide/chapters/content/en/glossary/asymptotic.md
- csfieldguide/chapters/content/en/glossary/extrapolation.md
- csfieldguide/chapters/content/en/glossary/greedy-algorithm.md
- csfieldguide/chapters/content/en/glossary/heuristic.md
- csfieldguide/chapters/content/en/glossary/interpolation.md
- csfieldguide/chapters/content/en/glossary/permutation.md
- csfieldguide/chapters/content/en/glossary/selection-sort.md
Contributes to #1017 
- In `algorithms-problems-and-speed-limits` There is an exercise to calculate how much time it would take to complete an algorithm on 100! items. This could use the Algorithm Timer interactive instead of requiring the calculations by hand. However even that interactive does not allow numbers as high as the activity requires (1 billion ops/s, though it could be modified to 1 million ops/s by 100 computers)
> Content fixes and add glossaries for Complexity and Tractability

- csfieldguide/chapters/content/en/computer-graphics/computer-graphics.md
- csfieldguide/chapters/content/en/computer-graphics/sections/drawing-lines-and-circles.md
- csfieldguide/chapters/content/en/computer-graphics/sections/graphics-transformations.md
- csfieldguide/chapters/content/en/computer-graphics/sections/whats-the-big-picture.md
- csfieldguide/chapters/content/en/glossary/cartesian-coordinate-system.md
- csfieldguide/chapters/content/en/glossary/computer-graphics.md
- csfieldguide/chapters/content/en/glossary/graphics-transform.md
- csfieldguide/chapters/content/en/glossary/graphics.md
- csfieldguide/chapters/content/en/glossary/rotation.md
- csfieldguide/chapters/content/en/glossary/scale.md
- csfieldguide/chapters/content/en/glossary/translation.md
Contributes to #1017 
Add glossaries:
Remove glossaries
> Add glossary entries for Computer Graphics Chapter

- docs/source/changelog.rst
Updates the paragraph in the changelog page to better reflect our intended use of the versioning system
> Update versioning system description to reflect its use in practice

- csfieldguide/chapters/content/en/computer-vision/computer-vision.md
- csfieldguide/chapters/content/en/computer-vision/sections/edge-detection.md
- csfieldguide/chapters/content/en/computer-vision/sections/face-recognition.md
- csfieldguide/chapters/content/en/computer-vision/sections/lights-camera-action.md
- csfieldguide/chapters/content/en/computer-vision/sections/noise.md
- csfieldguide/chapters/content/en/computer-vision/sections/thresholding.md
- csfieldguide/chapters/content/en/computer-vision/sections/whats-the-big-picture.md
- csfieldguide/chapters/content/en/glossary/computer-vision.md
- csfieldguide/chapters/content/en/glossary/edge-detection.md
- csfieldguide/chapters/content/en/glossary/image-noise.md
- csfieldguide/chapters/content/en/glossary/image-segmentation.md
- csfieldguide/chapters/content/en/glossary/thresholding.md
Relates to #1017 
New entries:
- Computer vision
- Edge detection
- Image segmentation
- Image-noise
- Thresholding
> Add glossary entries for Computer Vision Chapter

- csfieldguide/static/interactives/colour-matcher/README.md
- csfieldguide/static/interactives/colour-matcher/js/colour-matcher.js
Resolves #1166 
A thorough explanation of the bug can be found there
> Fix Colour Matcher bug where some bits did not flip when clicked on

- csfieldguide/chapters/content/en/glossary/bug.md
- csfieldguide/chapters/content/en/glossary/problem-domain.md
- csfieldguide/chapters/content/en/glossary/prototype.md
- csfieldguide/chapters/content/en/glossary/software.md
- csfieldguide/chapters/content/en/glossary/stakeholder.md
- csfieldguide/chapters/content/en/software-engineering/sections/analysis.md
- csfieldguide/chapters/content/en/software-engineering/sections/testing.md
- csfieldguide/chapters/content/en/software-engineering/software-engineering.md
I accidentally branched off the #1168 branch so will wait for that before marking it ready for review
Resolves #1017 
New entries:
- Bug
- Problem domain
- Prototype
- Software
- Stakeholder
Plus some content fixes
> Add glossary entries to Software Engineering chapter

- csfieldguide/static/scss/website.scss
> Remove float-left and float-right mixins.

- csfieldguide/static/interactives/binary-cards/css/binary-cards.scss
Resolves #1241 by slightly increasing the maximum width of the container in that interactive
> Fit binary cards in groups of 8 on large screens

- csfieldguide/chapters/content/en/data-representation/sections/images-and-colours.md
> Correct hex code in content

- csfieldguide/config/__init__.py
- docs/source/changelog.rst
self explanatory plus fix typos in changelog
> Merge Release/3.5.1 into develop & fix minor typos

- csfieldguide/chapters/content/en/complexity-and-tractability/sections/algorithms-problems-and-speed-limits.md
> Fix typo in Towers of Hanoi description

- csfieldguide/chapters/content/en/human-computer-interaction/sections/usability-heuristics.md
> Replace broken link.

- csfieldguide/templates/appendices/contributors.html
Adds myself as an Editor of CSFG; permission given by Jack & Tim
> update editors list

- csfieldguide/static/interactives/cfg-parsing-challenge/README.md
- csfieldguide/static/interactives/cfg-parsing-challenge/js/cfg-parsing-challenge.js
- csfieldguide/static/interactives/cfg-parsing-challenge/scss/cfg-parsing-challenge.scss
- csfieldguide/templates/interactives/cfg-parsing-challenge.html
- Always try to find valid expression, or throw an error. The number of attempts to randomly brute force an expression has been increased. Removes previous code that could result in invalid expressions.
- Show history of steps in interface.
Fixes #1377
> CFG Parser Challenge interactive changes

- csfieldguide/config/__init__.py
- docker-compose.prod.yml
- docs/changelog.rst
- Allow greater customisation for the website's Traefik routing rule.
> Release 3.8.4

- csfieldguide/config/settings/base.py
- csfieldguide/config/urls.py
- csfieldguide/config/views.py
- requirements/base.txt
- base.py: Added the cors dependencies and specified the allowed domains.
- base.txt: Added a requirement for cors.
- views.py: Added file with the view.
- urls.py: Added a new path for the view.
> Added CORS and view for getting the commit hash and version number for the dashboard.

- .github/workflows/test-and-deploy.yaml
- csfieldguide/general/management/commands/update_data.py
- csfieldguide/tests/general/management/test_updatedata_command.py
- dev
- docker-compose.prod.yml
- docs/developer/chapters.rst
- docs/developer/deployment.rst
- docs/getting_started/helper_commands.rst
Prior to these fixes, the codebase had a mix of update_data and updatedata references. Most significantly, the dev file listed the command as updatedata whereas it was actually update_data. This PR changes all references to update_data for consistency.
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and …
> Update data command fixed for consistency

- csfieldguide/chapters/content/en/coding-encryption/sections/the-key-distribution-problem.md
Change https://en.wikipedia.org/wiki/Padding_(cryptography to https://en.wikipedia.org/wiki/Padding_%28cryptography%29
> Escape Markdown URL with invalid closing bracket

- .github/workflows/test-and-deploy.yaml
- csfieldguide/config/__init__.py
- csfieldguide/static/interactives/parity/README.md
- csfieldguide/static/interactives/parity/css/parity.scss
- csfieldguide/static/interactives/parity/js/parity.js
- csfieldguide/static/interactives/product-code-check-digit-calculation/css/product-code-check-digit-calculation.scss
- csfieldguide/templates/interactives/parity.html
- docs/changelog.rst
- Add ability to hide mode headings and initial text in Parity interactive.
- Add ability to circle a row and column in Parity interactive by clicking on a grid reference label (or where they would be if they're hidden).
- Fix bug where edges of barcode where visible in the Product Code Check Digit Calculation interactive when embedded.  #1965
- Modify Docker deployment workflow to be in line with UCCSER repositories.  #1971
> Release 3.12.2

- README.md
- csfieldguide/config/__init__.py
- csfieldguide/static/interactives/pixel-viewer/README.md
- csfieldguide/static/interactives/pixel-viewer/js/pixel-viewer.js
- docker-compose.prod.yml
- docs/changelog.rst
- Add abiltiy to set initial zoom level in pixel-viewer interactive via URL parameter.
- Remove broken documentation link.
- Disable healthcheck on Docker task service to prevent deletion while running.
> Release 3.12.4

- csfieldguide/chapters/management/commands/_ChapterSectionHeadingsLoader.py
- csfieldguide/chapters/management/commands/_ChapterSectionsLoader.py
- csfieldguide/chapters/management/commands/_ChaptersLoader.py
- csfieldguide/chapters/management/commands/_GlossaryTermsLoader.py
- csfieldguide/config/__init__.py
- csfieldguide/curriculum_guides/management/commands/_CurriculumGuideSectionsLoader.py
- csfieldguide/curriculum_guides/management/commands/_CurriculumGuidesLoader.py
- csfieldguide/general/management/commands/update_data.py
- csfieldguide/interactives/management/commands/_InteractivesLoader.py
- csfieldguide/static/interactives/rgb-mixer/scss/rgb-mixer.scss
- docs/changelog.rst
- Update content rather than recreating it when `update_data` script is run.
- Dependency updates:
- Update crowdin/github-action from 1.4.16 to 1.5.0.
- Update sphinx-rtd-theme from 1.0.0 to 1.1.0.
> Release 3.12.6

- csfieldguide/chapters/content/en/coding-compression/sections/shannons-experiment.md
- csfieldguide/chapters/content/structure/coding-compression/sections/sections.yaml
Adds a section about Shannon's experiment. This contains a verto interactive tag, which means that the interactive also gets added to the list of interactives in "Coding - Compression" on the interactives page.
> Add section on shannons experiment

- csfieldguide/static/interactives/algorithm-timer/package-lock.json
- csfieldguide/static/interactives/matrix-simplifier/package-lock.json
> Update package lock

- csfieldguide/static/interactives/city-trip/package-lock.json
> Update package lock for city-trip

- csfieldguide/static/interactives/scene-editor/js/scene-editor.js
- csfieldguide/static/interactives/scene-editor/package-lock.json
- csfieldguide/static/interactives/scene-editor/package.json
- csfieldguide/templates/interactives/scene-editor.html
Albeit with slightly weird lighting
> Hotfix to get a working scene editor

- infrastructure/local/node/Dockerfile
https://github.com/uccser/cs-field-guide/issues/1647
> Use latest node LTS

- requirements/base.txt
https://github.com/uccser/cs-field-guide/issues/2486
bump django to 4.2.9 from 4.2.7
> bump django to 4.2.9 from 4.2.7

- csfieldguide/static/interactives/regular-expression-search/js/regular-expression-search.js
See https://github.com/uccser/cs-field-guide/issues/1833
> fix: Regular Expression Search interactive doesn't show syntax highlighting

- .github/workflows/test-and-deploy.yaml
Codecov is no longer working. Add access token to fix.
> Add codecov token to test and deploy workflow

- infrastructure/local/django/Dockerfile
- infrastructure/local/docs/Dockerfile
- infrastructure/local/node/Dockerfile
- infrastructure/production/django/Dockerfile
Update docker images to use: 
- debian bookworm
- python 3.11
> Update docker images: use debian bookworm and python 3.11
