uccser/cs-field-guide

- interactives/mips-assembler/README.md
Hey, this isn't a big deal either way. Maybe the thought here was that a github page would be more reliably safe for school than a personal website?
([Usually true](http://gizmodo.com/saucy-coder-scheduled-out-his-github-activity-to-spell-1586577467).)
It’s OK if you don’t change it, but I chose to have my own domain as my canonical identity online, over a profile on a third-party service.
Thoughts welcome.
> Change my name link to my personal website?

- text/en/chapters/coding-error-control.md
Fix several occurrences of "lets" > "let's", and "exam ple" >
"example".
> Fix typos in Error Control chapter

- text/en/chapters/formal-languages.md
Fixes small typos in the Formal Languages chapter.
Additionally, makes the glossary entry for Finite State Automaton display correctly.
*Put an `x` in the boxes that apply. You can also fill these out after creating the pull request. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your change.*
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc. Feel free to add any images that might be helpful to understand the initial problem/solution.
The fix for making …
> Fix typos in Formal Languages chapter

- interactives/2d-arrow-manipulations/js/main.js
There is a bug in `2d-arrow-manipulations` interactive that occurs when using config names including digits, e.g. `matrix-scale-translate-2`. It is caused by a faulty regex that matches incomplete label and makes the script look for a non-existent config file.
This PR fixes that.
> Handle digits in 2d-arrow-manipulation config name

- interactives/delay-analyser/css/delay-analyser.css
I increased the margin from the reset button so that it is further away from the grid.
The request to do this came from: 
https://github.com/uccser/cs-field-guide/issues/413
Just like JackMorganNZ suggested, I believe that the button is too close to the Delay Analyser and people can accidentally click on the reset button. We should move it just a little bit so that people won't reset it by mistake.  I also believe that this change makes the page looks much nicer.
This is my first pull request on Github and I appreciate you taking the time to look over this. I look forward to potentially running more fixes through this Github account.
Best regards, …
> Updated Delay Analyser reset button #413

- text/en/chapters/algorithms.md
Fix a typo in section 2.1.3 (Algorithm Correctness)
Changed: 
```diff
- with searching and sorting there exist multiple correct algorithms for the same problem.
+ with searching and sorting there are multiple correct algorithms for the same problem.
```
> Fix typo in section 2.1.3

- csfg
- docker-compose.yml
This pull request uses a unique port number for viewing the cs-field-guide website, when also working on the cs-unplugged project.
> Use unique port number for CSFG development

- interactives/base-calculator/js/base-calculator.js
Computed value is not correctly shown since it only shows the power of
base in certain place. For example when using calculator with base 10 it
shows only 1, 10, 100, 1000 etc. instead of seleted value in drop-down
multiplied with either 1, 10, 100, 1000 etc. depending on the place in the
number.
> Fix computed value

- csfieldguide/chapters/content/en/introduction/introduction.md
- csfieldguide/static/scss/website.scss
- csfieldguide/utils/custom_converter_templates/blockquote.html
- csfieldguide/utils/render_html_with_load_tags.py
Uses Verto 0.9.0 to display blockquote with custom template.
**Issue to raise:** `trans` tags within custom converter templates are not added to `django.po` when `makemessages` are run.
> Add blockquote in introduction

- csfg
This pull request changes the following in the `csfg` helper script:
- Compiles messages within the `static` command as compiling JavaScript translations creates a static file. It was created in the `update` command but this changes give a more expected behaviour.
- Add new command for updating and collecting static files: `dev update_static`
- Remove deletion of volumes as this deletes a Docker volume creating for storing node modules. Tidying Docker should be a user choice/action, not a project action.
Fixes #730
> Ensure JavaScript catalog is created when related commands are run

- csfieldguide/chapters/content/en/human-computer-interaction/sections/interface-usability.md
- csfieldguide/interactives/content/en/interactives.yaml
- csfieldguide/interactives/content/structure/interactives.yaml
- csfieldguide/templates/interactives/off-by-one.html
Replace 
with
So that the words can be translated. Relates to #732
> Add off-by-one interactive to replace image in HCI chapter

- csfieldguide/chapters/content/en/human-computer-interaction/sections/usability-heuristics.md
- csfieldguide/interactives/content/en/interactives.yaml
- csfieldguide/interactives/content/structure/interactives.yaml
- csfieldguide/templates/interactives/unexpected-error.html
Replace
with
So that the words can be translated. Relates to #732
> Add unexpected-error interactive to replace image in HCI chapter

- csfieldguide/chapters/content/en/algorithms/algorithms.md
- csfieldguide/chapters/content/en/artificial-intelligence/artificial-intelligence.md
- csfieldguide/chapters/content/en/coding-compression/coding-compression.md
- csfieldguide/chapters/content/en/coding-encryption/coding-encryption.md
- csfieldguide/chapters/content/en/coding-error-control/coding-error-control.md
- csfieldguide/chapters/content/en/coding-introduction/coding-introduction.md
- csfieldguide/chapters/content/en/complexity-and-tractability/complexity-and-tractability.md
- csfieldguide/chapters/content/en/computer-graphics/computer-graphics.md
- csfieldguide/chapters/content/en/computer-vision/computer-vision.md
- csfieldguide/chapters/content/en/data-representation/data-representation.md
- csfieldguide/chapters/content/en/formal-languages/formal-languages.md
- csfieldguide/chapters/content/en/human-computer-interaction/human-computer-interaction.md
- csfieldguide/chapters/content/en/introduction/introduction.md
- csfieldguide/chapters/content/en/network-communication-protocols/network-communication-protocols.md
- csfieldguide/chapters/content/en/programming-languages/programming-languages.md
- csfieldguide/chapters/content/en/software-engineering/software-engineering.md
- csfieldguide/chapters/management/commands/_ChapterSectionsLoader.py
- csfieldguide/chapters/management/commands/_ChaptersLoader.py
- csfieldguide/templates/chapters/chapter.html
- csfieldguide/templates/chapters/chapter_section.html
- csfieldguide/utils/BaseLoader.py
- csfieldguide/utils/custom_converter_templates/chapter-section/heading.html
- csfieldguide/utils/custom_converter_templates/chapter/heading.html
Uses custom templates depending on depth of document.
Also removes "What's the big picture?" heading from all chapters, and adds link to chapter from chapter section in page header.
Fixes #703
>  Fix bug where section numbers weren't correct

- csfieldguide/chapters/content/en/human-computer-interaction/sections/usability-heuristics.md
- csfieldguide/interactives/content/en/interactives.yaml
- csfieldguide/interactives/content/structure/interactives.yaml
- csfieldguide/static/interactives/binary-mode-calculator/scss/binary-mode-calculator.scss
- csfieldguide/templates/interactives/binary-mode-calculator.html
Replace
with
So that the words can be translated. Relates to #732
> Add binary-mode-calculator interactive to replace image in HCI chapter

- csfieldguide/gulpfile.js
- csfieldguide/package.json
- docker-compose.yml
Remove usage of babel and use terser package. This results in less complicated JavaScript (though our JavaScript should have good compatibility already) and a smaller file size (only 2kb smaller).
Fixes #750 
Once this pull request has been merged, a new issue should be raise to check browser compatibility.
> Fix compilation of production JavaScript

- csfieldguide/chapters/management/commands/_ChapterSectionsLoader.py
- csfieldguide/templates/chapters/chapter.html
- csfieldguide/templates/chapters/chapter_section.html
- csfieldguide/tests/chapters/loaders/assets/chapter-sections/en/non-sequential-section-numbers/non-sequential-section-numbers-section-1.md
- csfieldguide/tests/chapters/loaders/assets/chapter-sections/en/non-sequential-section-numbers/non-sequential-section-numbers-section-2.md
- csfieldguide/tests/chapters/loaders/assets/chapter-sections/en/non-sequential-section-numbers/non-sequential-section-numbers-section-4.md
- csfieldguide/tests/chapters/loaders/assets/chapter-sections/structure/non-sequential-section-numbers/non-sequential-section-numbers.yaml
- csfieldguide/tests/chapters/loaders/test_chapter_sections_loader.py
Resolves #773 
Expands on #773 by:
- showing 'not-available-warning' when a chapter or chapter section is not translated in the current language.
- Greying out chapter section links if they are not translated in the current language
> Consistent numbering for chapter sections

- csfieldguide/chapters/content/en/coding-compression/sections/the-whole-story.md
- csfieldguide/chapters/content/en/computer-graphics/sections/further-reading.md
- csfieldguide/chapters/content/en/computer-graphics/sections/graphics-transformations.md
- csfieldguide/chapters/content/en/computer-vision/sections/further-reading.md
- csfieldguide/chapters/content/en/data-representation/sections/images-and-colours.md
- csfieldguide/chapters/content/en/data-representation/sections/numbers.md
- csfieldguide/chapters/content/en/formal-languages/sections/finite-state-automata.md
- csfieldguide/chapters/content/en/network-communication-protocols/sections/further-reading.md
This PR fixes typos and broken links in the content.
Issues to be closed after merging: #782, #784, #785, #789. #781 can also be closed, note that not all links marked as broken by linkie are actually broken, rather they just take you to a page that requires registration/log in before you can proceed, as indicated by the text in the field guide.
> Typo and broken link fixes

- csfieldguide/chapters/content/en/coding-error-control/coding-error-control.md
- csfieldguide/chapters/content/en/coding-error-control/sections/check-digits-on-barcodes.md
- csfieldguide/chapters/content/en/coding-error-control/sections/further-reading.md
- csfieldguide/chapters/content/en/coding-error-control/sections/the-parity-magic-trick.md
- csfieldguide/chapters/content/structure/structure.yaml
- csfieldguide/interactives/content/structure/interactives.yaml
- csfieldguide/static/interactives/parity/js/parity.js
- csfieldguide/templates/interactives/parity.html
This PR activates the Coding Error Control chapter. It includes some typo/formatting fixes along with a change to the parity interacitve (to count even black squares - (not white) which relates to #769.
NOTE: iframes are not resizing but will be addressed in #827
> Activate Coding Error Control chapter

- csfieldguide/interactives/content/en/interactives.yaml
This fixes a minor issue where the names of two Interactives in the Appendix were not consistent with surrounding Interactive names. They have been renamed to `MIPS Assembler` and `MIPS Simulator` respectively.
> Fix names of MIPS interactives in appendix

- csfieldguide/static/interactives/colour-matcher/README.md
- csfieldguide/static/interactives/colour-matcher/js/colour-matcher.js
- csfieldguide/static/interactives/colour-matcher/scss/colour-matcher.scss
- csfieldguide/static/interactives/mips-assembler/README.md
- csfieldguide/static/interactives/mips-simulator/README.md
- csfieldguide/static/interactives/mips-simulator/css/mips-simulator.scss
- csfieldguide/templates/interactives/colour-matcher.html
This fixes the spelling of 'hexadecimal' throughout the Colour Matcher interactive (resolves #879)
Also, because I accidentally did it on the same branch, this resolves minor issues I found in the MIPS interactives:
- Remove references to the CSFG v2.0 `base-files` folder
- Fix padding issue in the Simulator interactive
- Change credit given to Alan Hogan, as the original wording could imply that he created MIPS itself
> Fix spelling of hexadecimal in colour matcher interactive

- csfieldguide/static/scss/_core-variables.scss
This PR brings back all of bootstraps theme colours as they were accidentally overwritten in #932. 
Not super happy with this solution as we have to copy over the _whole_ of the `$theme-colors` map into the sass file. The only way I could find how to update just the one theme colour would mean we would have to import bootstraps` _variables.scss` file before our `_core-variables.scss` file; which will break other things.
There's a discussion about it here: https://github.com/twbs/bootstrap/issues/23112
If anyone wants to dig further go for it.
Resolves #934
> Copy over theme-colours object.

- csfieldguide/static/scss/codemirror.scss
Moved the css import to a new file in #941 and forgot to update the file path... Resolves #928
> Set correct file path for import of codemirror css

- csfieldguide/static/interactives/unicode-chars/README.md
- csfieldguide/static/interactives/unicode-chars/css/unicode-chars.css
- csfieldguide/static/interactives/unicode-chars/css/unicode-chars.scss
- csfieldguide/static/interactives/unicode-chars/js/unicode-chars.js
- csfieldguide/templates/interactives/unicode-chars.html
> Improve usability of unicode chars and add readme

- csfieldguide/chapters/content/en/algorithms/algorithms.md
Resolves #899 
Things of note I found when using the syntax `[text](link)`:
- If link is a url it will link to the url (as expected)
- If link == `/link` (ie is prefixed with `/`) it will append link to the base url (e.g: `localhost:81/link`). This becomes useful because the language code is added automatically (e.g: `localhost:81/en/link`)
- If link is not prefixed with `/`, link will be appended to the current url (e.g: `[full-current-url]/link`). This is what is done here
> Fix old chapter link syntax in Algorithms chapter

- csfieldguide/templates/interactives/image-bit-comparer.html
- csfieldguide/templates/interactives/jpeg-compression.html
- csfieldguide/templates/interactives/pixel-viewer.html
Add `crossorigin="anonymous"` to canvas elements so that canvas elements are no longer tainted by cross-origin data.
See https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image for in depth info.
Note that the `viola-jones` interactive also uses canvas elements so it will need to also be updated in #924 
(related to #878)
> Add crossorigin attribute to canvas elements.

- csfieldguide/static/interactives/image-bit-comparer/js/image-bit-comparer.js
- csfieldguide/static/interactives/jpeg-compression/js/jpeg-compression.js
- csfieldguide/static/interactives/pixel-viewer/js/pixel-viewer.js
- csfieldguide/static/interactives/viola-jones-face-detector/js/viola-jones.js
In #955 we set the crossorigin attribute to 'anonymous' in the HTML templates. However we also needed to set this on canvas elements in the JavaScipt files (for the canvas elements that get canvas methods run on them - such as getImageData).
Will not know if this resolves our problem until it is merged into develop..
Relates to #878
> Prevent canvas from being tainted by setting the crossorigin attribute in the JavaScript..

- csfieldguide/chapters/views.py
- csfieldguide/templates/chapters/chapter_section.html
Resolves #884 
For any chapter number `x`, the end of the chapter will attempt to link to chapter number `x+1`. If it doesn't find one it doesn't make the link, even if for example chapter number `x+2` does exist. On the current version of the dev site (at time of writing), chapters 3 (prog lang) and 13 (comp vision) are commented out as they are not ready for release. As such chapters 2 and 12 (as well as the final one of course) won't have links to the next chapters. This is only a minor issue because we can expect that all chapters will be available on release.
If there is a missing chapter section number an error is thrown during the build/update process, so it will never link to the next chapter with chapter sections still remaining
While doing this I noticed several sentences …
> At the end of each chapter, link to the next

- csfieldguide/static/interactives/pixel-viewer/README.md
- csfieldguide/templates/interactives/pixel-viewer.html
Resolves #964, though I didn't worry about having the option only appear if the interactive was loaded without a config
> add configuration options to pixel viewer

- csfieldguide/chapters/views.py
- csfieldguide/static/js/website.js
- csfieldguide/static/scss/website.scss
- csfieldguide/templates/base.html
- csfieldguide/tests/chapters/views/test_glossary_view.py
- csfieldguide/utils/custom_converter_templates/glossary-link.html
Currently glossary terms/links are not distinguishable from plain text. This PR adds a dotted line under the glossary terms/links.
It also adds the `translated` json data field to indicate whether a translation for the current language exists for the glossary definition. This fixes the issue of a translation error appearing even though the translation is available (`data.translated` was always undefined so an error was always displayed).
Note that I have not been able to test this for languages other than English as there are currently no glossary links in other language markdown files.
Resolves #862
> Highlight glossary terms appropriately.

- csfieldguide/static/scss/website.scss
- csfieldguide/templates/chapters/chapter_section.html
Resolves #949 
The d-flex options override justify-left/-right when applicable. This allows the buttons to maintain the same height if one of them has to wrap text
> Align chapter section buttons better if they don't fit in one line

- csfieldguide/chapters/content/es/human-computer-interaction/human-computer-interaction.md
- csfieldguide/chapters/content/es/human-computer-interaction/sections/the-whole-story.md
Comments that should not be shown are being shown to users due to a Verto tag being translated. In future all comment strings needs to be disabled on Crowdin.
Fixes #969
> Revert syntax for translated Verto tags in Spanish

- csfieldguide/chapters/content/en/computer-graphics/sections/further-reading.md
- csfieldguide/chapters/content/en/formal-languages/sections/grammars-and-parsing.md
Relates to #781 
Does not resolve as https://csfieldguide.org.nz should be fixed with 3.0 release. Linkie was picking up the names for the links as real links so I changed them to something more human readable.
> Fix 2 broken links.

- csfieldguide/templates/appendices/index.html
Links to https://cs-field-guide.readthedocs.io/en/latest/index.html from the appendices
> Add link to documentation from appendices

- csfieldguide/static/interactives/binary-cards/css/binary-cards.scss
Resolves #1056 
Adds a rule so that the `backface-visibility: hidden;` css rule only applies in firefox (the issue this rule solved, numbers being visible when the card is flipped, does not appear to be an issue on chrome)
> Fix binary cards not flipping back to white on chrome

- csfieldguide/static/scss/website.scss
- csfieldguide/templates/base.html
Adds blue background to dropdown navigation when in student mode and gradient background when in teacher mode. See below:
Relates to #1054. Does not resolve as there is a comment on this issue regarding scrolling but I cannot test it on desktop.
> Add background to navigation dropdown.

- csfieldguide/chapters/urls.py
- csfieldguide/curriculum_guides/urls.py
- csfieldguide/general/urls.py
This PR redirects https://csfieldguide.org.nz/index.html to https://csfieldguide.org.nz/ and tidies some code in the `urls.py` files.
~~HELP WANTED:~~
- Currently the redirects for permalinks are incorrect. For example `/chapters/algorithms.html#searching` should redirect to `/chapters/algorithms/searching/` but instead it redirects to `http://localhost:81/en/chapters/algorithms/#searching`.
- Here are the two redirects I found that do not work:
In `chapters/urls.py`:
```
url(
r"^(?P<chapter_slug>[-\w]+).html#(?P<chapter_section_slug>[-\w]+)$",
RedirectView.as_view(permanent=True, pattern_name="chapters:chapter_section"),
),
```
In `curriculum_guides/urls.py`:
```
url(
r"^(?P<curriculum_guide_slug>[-\w]+)/index.html#(?P<curriculum_guide_section_slug>[-\w]+)$", …
```
> URL redirects

- csfieldguide/static/interactives/sorting-algorithms/js/sorting-algorithms.js
- csfieldguide/templates/interactives/sorting-algorithms.html
This PR is not important
Adds a 'Reshuffle weights' button to the sorting algorithms interactive.
This button resets the interactive *with new weight values* so that a subsequent sort doesn't give the same result. Also makes it more clear (implies) that the existing 'reset' button does not reshuffle the weights
> Add reshuffle weights button to Sorting Algorithms interactive

- csfieldguide/templates/base.html
Adds the class `form-inline` to the homepage search bar so that it isn't overly long on mobile screens
> Reduce length of search bar on mobile

- csfieldguide/chapters/content/en/computer-vision/sections/face-recognition.md
Resolves #367. Was kind of hard to mention nicely in the text since we dump a whole bunch of links in this section. Should be better once #409 is completed.
> Add link to Vox video in computer vision chapter.

- LICENCE-CONTENT
- README.md
Amends the LICENCE-CONTENT file to exclude:
- Images located within the `csfieldguide/static/img/chapters/` directory that are prefixed with `xkcd`
- `csfieldguide/static/img/third-party/`
- `csfieldguide/static/img/logos/`
as they may be subject to different licences
> Amend content licence to exclude certain properties we don't own

- csfieldguide/static/interactives/rsa-decryption/js/rsa-decryption.js
- csfieldguide/static/interactives/rsa-encryption/js/rsa-encryption.js
- csfieldguide/static/interactives/rsa-key-generator/js/rsa-key-generator.js
- csfieldguide/templates/interactives/rsa-decryption.html
- csfieldguide/templates/interactives/rsa-encryption.html
- csfieldguide/templates/interactives/rsa-key-generator.html
Implements a fix I was meant to do in #1123 
The `e` component of keys is now split into pairs of characters (bytes) for consistency
> Fix consistency in RSA interactives

- .arnold.yaml
Adds the `third-party-licences` directory to the list of directories Linkie will not run over when checking for broken links. We cannot change licences to fix/remove broken links so instead we can whitelist them so they do not appear as errors
Relates to #1153
> Exclude licences directory from Linkie

- csfieldguide/static/scss/website.scss
The problem is that we have `overflow: auto;` set on our `#body-content` div which is causing the current page to be clipped with a scrollbar instead of showing all of the content (that spans across multiple pages) in print preview.
To fix this I simply added a print media query that overrides this overflow property when printing.
This only resolves the issue in Chrome. Currently Firefox print preview breaks on anything that uses flex styling, see https://bugzilla.mozilla.org/show_bug.cgi?id=939897.
Relates to #1110
> Fix print preview to have ability to print more than just the current page in Chrome.

- csfieldguide/chapters/content/en/computer-graphics/sections/graphics-transformations.md
We now use an entirely different teapot mesh in the `scene-editor` interactive.~~The new mesh has 289 points instead of 3644. Have updated the sentence to match.~~
We do not know how many points there are exactly now. Unless someone knows how to calculate how many there are?
> Update sentence about mesh points in CG chapter.

- csfieldguide/chapters/content/en/algorithms/sections/sorting.md
Resolves #1192 
I have done a project wide search for the old notation and this is the only place the old notation appears.
> Fix formatting for mathematical equations in algorithms chapter.

- csfieldguide/chapters/content/en/computer-graphics/sections/graphics-transformations.md
Addresses some of the issues raised in #1197 
> In section 12.2 Before the block interactives it would be good to explicitly say what directions negative and positive numbers will move the box in.
> The content mentions point (3, 1) as the rightmost corner of the shape. This refers to the original arrow. The rightmost points of the current shape are (2, 3) and (2, 1)
> Resolve some issues with CG chapter

- csfieldguide/static/interactives/pixel-viewer/js/pixel-viewer.js
Inconsistencies have been occurring on the pixel viewer interactive regarding CORS requests. After some investigating we noticed:
- Upon disabling cache through dev tools we no longer got a CORS error.
- Two requests for images were being made; one of which was being made through jquery.
- In the response headers there is an attribute `sec-fetch-mode` that has the value `no-cors`.
- Only the default image was triggering the CORS error.
We suspect that the jquery request is being cached first (which doesn't have CORS headers), and then the second request is made (with CORS headers) but during this request Chrome fetches from the cache (but the CORS headers aren't cached due to the first request) which results in a CORS error on the second fetch.
With this change we see only one request …
> Set crossorigin attribute on the default image in pixel viewer

- csfieldguide/chapters/content/en/data-representation/sections/whats-the-big-picture.md
- csfieldguide/static/interactives/binary-cards/README.md
- csfieldguide/static/interactives/binary-cards/css/binary-cards.scss
- csfieldguide/static/interactives/binary-cards/js/binary-cards.js
- csfieldguide/templates/interactives/binary-cards.html
**Changes**
- Add input box to the binary cards interactive that allows the user to change how many cards are displayed. This can be anywhere from 1 to 16 cards inclusive.
- Add `input` URL parameter. Can be set to either 'true' or 'false to show or hide the input box respectively. Default is set to 'true'.
**Notes**
- The interactive now loads 16 (the max) cards first, before hiding cards to show the default 8 cards (or the value of the `digits` URL parameter if it is passed). Mostly done to prevent rewriting majority of the code. This allows us to easily hide and show cards dynamically when the user interacts with the input box.
- If a `start` parameter is passed that is less than 16 (or whatever the max is set to) letters long, e.g `BBBBB` we add padding to the start of the string so …
> Allow users to choose the number of cards displayed in binary cards interactive with input box

- csfieldguide/chapters/content/en/coding-compression/sections/general-purpose.md
- csfieldguide/static/interactives/lzss-compression/js/lzss-compression.js
- csfieldguide/static/interactives/lzss-compression/scss/lzss-compression.scss
- csfieldguide/templates/interactives/lzss-compression.html
This PR addresses a bug in the LZSS interactive where the text is not being encoded correctly for some strings.
**The problem** 
The sliding window and encoded message are initialised to the first 6 characters. This means the first 6 characters can never be pointers - even if there are repeating strings within these 6 characters. This does not work correctly for small strings or for strings of a repeating nature, e.g `ababababababab`.
**Changes**
- Initialise sliding window and encoded message to only contain the first 2 characters (minimum match length).
- Raise max length of match to 16 (4 bits). This used to be 5 which is unusually small.
- Replace space characters in the encoded message with the open box character. This addresses part of #1253
- Add small note under the encoded text …
> Fix issue with LZSS compression interactive encoding text incorrectly

- csfieldguide/static/interactives/cmy-mixer/README.md
- csfieldguide/static/interactives/cmy-mixer/js/cmy-mixer.js
- csfieldguide/static/interactives/cmy-mixer/package.json
- csfieldguide/static/interactives/rgb-mixer/README.md
- csfieldguide/static/interactives/rgb-mixer/js/rgb-mixer.js
- csfieldguide/static/interactives/rgb-mixer/package.json
- csfieldguide/templates/interactives/cmy-mixer.html
- csfieldguide/templates/interactives/rgb-mixer.html
Resolves #1290 
- Add URL parameter `hex=true|false`
- Add radio buttons for hexadecimal/decimal option
- Allow input box and slider pips to use hexadecimal values when required
- Implement ability to switch between hex and decimal versions of input box and sliders
I don't think it's worth it to try and enforce a two-digit hexadecimal (i.e. 00 - 0F instead of 0 - F), while still allowing users to type in the values they want to set the sliders to
> Implement hex v decimal option to Colour Mixer interactives

- csfieldguide/static/interactives/pixel-viewer/README.md
- csfieldguide/static/interactives/pixel-viewer/js/pixel-viewer.js
- csfieldguide/templates/interactives/pixel-viewer.html
**Changes**
- Users now have 3 different options for how colour codes should be displayed.
- Decimal (as separate RGB values) **(default)**
- Hexadecimal (as separate RGB values)
- Hexadecimal (web colour)
- Add optional URL parameter `colour-code` that sets what colour code the interactive loads with. Values are:
- `rgb` (default)
- `rgb-hex`
- `hex`
- Update README.
Resolves #1277
> Add ability to show colour codes in Hexadecimal on Pixel Viewer

- csfieldguide/static/interactives/pixel-viewer/README.md
- csfieldguide/static/interactives/pixel-viewer/js/pixel-viewer.js
- csfieldguide/templates/interactives/pixel-viewer.html
The mode is accessed with parameters `?mode=brightness&colour-code=brightness`. It cannot be accessed in any other way
`?mode=brightness` sets the pixels to greyscale, sets the description and doesn't add the thresholder.
`?colour-code=brightness` only activates if mode==brightness.
It sets the values displayed to be the R component of the colour (it's greyscale so this is fine), and it hides the colour format radio buttons as well as the config selector.
Optionally `&picturepicker` can be added to include the extra default pictures
> Add special brightness mode to Pixel Viewer

- csfieldguide/general/urls.py
- csfieldguide/static/interactives/cmy-mixer/README.md
- csfieldguide/static/interactives/cmy-mixer/js/cmy-mixer.js
- csfieldguide/static/interactives/cmy-mixer/scss/cmy-mixer.scss
- csfieldguide/static/interactives/pixel-viewer/README.md
- csfieldguide/static/interactives/pixel-viewer/js/pixel-viewer.js
- csfieldguide/static/interactives/rgb-mixer/README.md
- csfieldguide/static/interactives/rgb-mixer/js/rgb-mixer.js
- csfieldguide/templates/interactives/cmy-mixer.html
- `pixelmania-2` redirects to a different url but the same functionality
- The original `mode=pixelmania` option is deprecated but still works
- New parameters: `hide-selector=true|false` for the rgb/hex radio options & `pixelmania` for the logo
- New URL parameter `hide-selector=true|false` for the rgb/hex radio options
- No `pixelmania` parameter because it wasn't used for Pixelmania
- Layout and css rules brought inline with RGB Mixer
- Display of cmy colour code in colour box
- There is no equivalent hex code for CMY so it is ~left blank~ also cmy colour code but using hex values
Resolves #1306
> Fix up Pixel Viewer and RGB mixer plus modernise CMY mixer

- .dockerignore
This fixes a bug where dockerignore used the csunplugged filenames (it was probably a straight copy from CSU) rather than csfg ones.
> Fix dockerignore folder names

- csfieldguide/static/interactives/algorithm-timer/README.md
- csfieldguide/static/interactives/algorithm-timer/js/algorithm-timer.js
- csfieldguide/templates/interactives/algorithm-timer.html
Resolves #1332 
- If the number of steps required (based on `n` & the complexity) is greater than `10^32`, the calculation won't be made
- New limit is `10^16` processors/operations per second
- One for an invalid number, one for a number that's too high
> Improve limitations for Algorithm Timer interactive

- csfieldguide/config/__init__.py
- docker-compose.prod.yml
- docs/changelog.rst
**Release date:** 6th September 2021
**Changelog:**
- Modify network name for production deployments.
> Release 3.8.2

- csfieldguide/chapters/content/en/data-representation/sections/text.md
- csfieldguide/templates/appendices/contributors.html
Previous binary solution spelled 'wawtr'. Updated to spell 'water'.
> Fix solution to 'Representation for water' 

- .github/workflows/test-and-deploy.yaml
- csfieldguide/templates/appendices/contributors.html
- dev
- docker-compose.local.yml
- infrastructure/local/node/Dockerfile
On multi-user systems, such as the University of Canterbury linux systems, it appears that the node user created by the Nodejs docker base has a different UID to the host user. This is a problem because we use a bind mount, which retains the host users permissions, meaning that the node user doesn't have permission to access the mounted files.
This PR sets the UID of the node user to the value of the $UID bash shell variable to fix the permission issue.
> Set UID of node user to the UID of the host user

- requirements/test.txt
Reverts uccser/cs-field-guide#2078
> Revert "Bump pydocstyle from 6.2.3 to 6.3.0"

- docs/author/writing_guide.rst
Add documentation about the different types of panels available with custom styles for authors in CSFG. Previously, the only way to know would be to look through the code, or look at other sections on the website as examples.
> Add information about the list of panel types

- csfieldguide/gulpfile.mjs
- csfieldguide/package-lock.json
- csfieldguide/package.json
- csfieldguide/static/interactives/scene-editor/js/scene-editor.js
- csfieldguide/templates/interactives/scene-editor.html
- csfieldguide/tests/helpers.py
Fixing issue: https://github.com/uccser/cs-field-guide/issues/1659
The scene editor broke due to breaking (because of our build process) changes to `three.js`. 
- Some deprecated API changes have been fixed.
- The `OrbitControls` add-on now uses ES modules in a way that browserify doesn't support. `three.js` plans to move to ES [modules exclusively and recomends using `vite`](https://threejs.org/docs/index.html#manual/en/introduction/Installation)
- To fix this I've added `babelify` which  is a `browserify` transform that transpiles (using `babel`) before `browserify` does it's thing. It is set up to transpile three.js and all other non node_module js to a browserify supported form. 
- A handy side effect of this is that interactives and other JS can now be written using ES2015+ syntax …
> Issue/1659babelify: Fixing the scene editor interactive using babel

- csfieldguide/chapters/content/en/network-communication-protocols/sections/the-whole-story.md
- csfieldguide/templates/appendices/contributors.html
Reworded "the mac" to macOS for clarity, and replaced link to deleted Apple KB article with link to Apple tcpdump documentation, which seems to be the equivalent at present
Feel free to add any images that might be …
> fix (currently-broken) link to tcpdump docs and reword sentence

- csfieldguide/static/interactives/cmy-mixer/js/cmy-mixer.js
- csfieldguide/static/interactives/rgb-mixer/js/rgb-mixer.js
- csfieldguide/templates/interactives/cmy-mixer.html
- csfieldguide/templates/interactives/rgb-mixer.html
Minor fix: The CMY and RGB colour mixers are meant to appear on the same page ([5.5](https://www.csfieldguide.org.nz/en/chapters/data-representation/images-and-colours/)), but the radio buttons for both interactives have the same names and IDs, contrary to most other elements in those interactives. This pull request gives the radio buttons different names and IDs, consistent with other elements, so that clicking a radio button in one interactive doesn't produce unexpected behaviours in the other.
> Namespace radio buttons for CMY/RGB colour mixers

- csfieldguide/interactives/views.py
https://github.com/uccser/cs-field-guide/issues/1181
> fix: 'No interactives' note missing from interactives index page: software engineering

- csfieldguide/locale/en/LC_MESSAGES/djangojs.po
- csfieldguide/static/interactives/pixel-viewer/js/pixel-viewer.js
- csfieldguide/templates/interactives/pixel-viewer.html
- Make tool tips for zoom buttons
- Tool tip visible on button show to direct user towards them
- When resize happens, re-show tool tips
- Add icons for Zoom In and Zoom Out
https://github.com/uccser/cs-field-guide/issues/788
> Improve pixel viewer interactive's UI clarity

- csfieldguide/chapters/content/en/big-data/sections/analysis.md
- csfieldguide/chapters/content/en/coding-error-control/sections/the-parity-magic-trick.md
- csfieldguide/chapters/content/en/coding-introduction/sections/further-reading.md
- csfieldguide/chapters/content/en/complexity-and-tractability/sections/other-intractable-problems.md
- csfieldguide/chapters/content/en/computer-graphics/sections/further-reading.md
- csfieldguide/chapters/content/en/software-engineering/sections/further-reading.md
- csfieldguide/templates/appendices/contributors.html
Make "Entropy and information theory" inline link compatible with older markdown implementations.
fixes #2565
Newer Markdown implementations (e.g. GitHub's as of this writing) properly render an inline link[0] whose link destination[1] includes parenthesis. Older ones fail, and, as a result, what should be rendered as:
href="https://en.wikipedia.org/wiki/Entropy_(information_theory)"
is instead rendered as:
href="https://en.wikipedia.org/wiki/Entropy_(information_theory"
(closing parenthesis elided/wrong URL)
Wrapping the link destination within angle brackets solves that issue in a way that should be forward-compatible.
[0] https://spec.commonmark.org/0.31.2/#inline-link
[1] https://spec.commonmark.org/0.31.2/#link-destination
Describe the big picture of your changes here to communicate …
> Fix link to "Entropy (information theory)" Wikipedia entry

- .readthedocs.yaml
Added a configuration file to hopefully fix readthedocs not loading. Can't test without pull request. 
https://github.com/uccser/cs-field-guide/issues/2611
> Added readthedocs yaml
